/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Group: typeof import('./src/components/Group.vue')['default']
    IconBase: typeof import('./src/components/Icon/IconBase.vue')['default']
    IconBaseWithBadge: typeof import('./src/components/Icon/IconBaseWithBadge.vue')['default']
    IconBell: typeof import('./src/components/Icon/IconBell.vue')['default']
    IconBellOff: typeof import('./src/components/Icon/IconBellOff.vue')['default']
    IconCheckmark: typeof import('./src/components/Icon/IconCheckmark.vue')['default']
    IconCheckmarkEmpty: typeof import('./src/components/Icon/IconCheckmarkEmpty.vue')['default']
    IconCheckmarkFilled: typeof import('./src/components/Icon/IconCheckmarkFilled.vue')['default']
    IconClose: typeof import('./src/components/Icon/IconClose.vue')['default']
    IconEdit: typeof import('./src/components/Icon/IconEdit.vue')['default']
    IconLightbulb: typeof import('./src/components/Icon/IconLightbulb.vue')['default']
    IconLoading: typeof import('./src/components/Icon/IconLoading.vue')['default']
    IconMoon: typeof import('./src/components/Icon/IconMoon.vue')['default']
    IconSettings: typeof import('./src/components/Icon/IconSettings.vue')['default']
    IconStar: typeof import('./src/components/Icon/IconStar.vue')['default']
    IconSun: typeof import('./src/components/Icon/IconSun.vue')['default']
    IoBrokerStatusIndicator: typeof import('./src/components/IoBrokerStatusIndicator.vue')['default']
    LabelValue: typeof import('./src/components/LabelValue.vue')['default']
    LampIcon: typeof import('./src/components/LampIcon.vue')['default']
    Light: typeof import('./src/components/Light.vue')['default']
    MultiStateSwitch: typeof import('./src/components/MultiStateSwitch.vue')['default']
    NotificationPanel: typeof import('./src/components/NotificationPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsModal: typeof import('./src/components/SettingsModal.vue')['default']
    TempDisplay: typeof import('./src/components/TempDisplay.vue')['default']
    ToggleSwitch: typeof import('./src/components/ToggleSwitch.vue')['default']
    WindowState: typeof import('./src/components/WindowState.vue')['default']
  }
}
